// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Apply(arg1:Array<main.Monitor>):Promise<Array<main.Monitor>>;

export function GetMonitors():Promise<Array<main.Monitor>>;
